# Generated by Django 6.0.6 on 2026-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ride_date', models.DateField(blank=True, null=True, verbose_name='Date de la sortie')),
                ('start_city', models.CharField(blank=True, max_length=120, verbose_name='Ville de départ')),
                ('distance_m', models.FloatField(default=0, verbose_name='Distance (m)')),
                ('elevation_gain_m', models.FloatField(default=0, verbose_name='Dénivelé positif (m)')),
                ('geometry', models.JSONField(blank=True, default=list, verbose_name='Tracé (points lat/lng)')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('strava', 'Strava'), ('ridewithgps', 'RideWithGPS')], default='manual', max_length=20, verbose_name='Source')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='Identifiant externe')),
                ('strava_url', models.URLField(blank=True, verbose_name='Lien Strava')),
                ('ridewithgps_url', models.URLField(blank=True, verbose_name='Lien RideWithGPS')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Vignette')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
                'ordering': ['-ride_date', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_source_external_id')],
            },
        ),
    ]
