# Generated by Django 6.0.6 on 2026-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rwgps_route_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID parcours RideWithGPS'),
        ),
        migrations.AddField(
            model_name='ride',
            name='strava_activity_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID activité Strava'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Identifiant externe (saisie manuelle)'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('strava_activity_id', ''), _negated=True), fields=('strava_activity_id',), name='unique_strava_activity_id'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.UniqueConstraint(condition=models.Q(('rwgps_route_id', ''), _negated=True), fields=('rwgps_route_id',), name='unique_rwgps_route_id'),
        ),
    ]
