# Generated by Django 6.0.6 on 2026-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_rwgps_route_id_ride_strava_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='strava_elevation_gain_m',
            field=models.FloatField(blank=True, help_text="Renseigné par l'import Strava. Affiché de préférence au dénivelé RideWithGPS, qui sous-estime. Vider ce champ pour retomber sur le dénivelé positif ci-dessus.", null=True, verbose_name='Dénivelé positif Strava (m)'),
        ),
    ]
