# Generated by Django 6.0.6 on 2026-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_strava_elevation_gain_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='elevation_profile',
            field=models.JSONField(blank=True, default=list, help_text='Liste de points [distance en mètres, altitude en mètres].', verbose_name="Profil d'altitude (distance/élévation)"),
        ),
    ]
